# Generated by Django 4.0.3 on 2022-06-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clayful_token',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='클레이풀 토큰'),
        ),
    ]
