# Generated by Django 4.0.3 on 2024-04-22 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_clayful_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='clayful_token',
        ),
    ]
