# Generated by Django 4.2 on 2024-06-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_emailverifier_id_alter_phoneverifier_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='marketing_agreed',
            field=models.BooleanField(default=False, verbose_name='마케팅 동의'),
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_agreed',
            field=models.BooleanField(default=False, verbose_name='약관 동의'),
        ),
    ]
