# Generated by Django 4.2 on 2024-07-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_points_remove_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marketing_agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마케팅 동의 / 취소 일자'),
        ),
    ]
