# Generated by Django 4.2 on 2024-08-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_marketing_agreed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='휴대폰'),
        ),
    ]
