# Generated by Django 4.0.3 on 2022-06-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='공지사항 제목')),
                ('sub_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='공지사항 부제목')),
                ('url', models.URLField(verbose_name='본문 url 주소')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
            },
        ),
    ]
