# Generated by Django 4.2 on 2024-06-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='url',
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='본문 내용'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='제목'),
        ),
    ]
