# Generated by Django 4.2 on 2024-06-15 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BigSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='대주제')),
            ],
            options={
                'verbose_name': '주제',
                'verbose_name_plural': '주제',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='지역')),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역',
            },
        ),
        migrations.CreateModel(
            name='SmallSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='소주제')),
                ('big_subject', models.ForeignKey(max_length=512, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.bigsubject', verbose_name='대주제')),
            ],
            options={
                'verbose_name': '주제',
                'verbose_name_plural': '주제',
            },
        ),
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='문제 셋 이름')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('type', models.CharField(blank=True, choices=[('P', '연습'), ('A', '실전')], max_length=1)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.region', verbose_name='지역')),
            ],
            options={
                'verbose_name': '문제 세트',
                'verbose_name_plural': '문제 세트',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, null=True, verbose_name='고유 번호')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='제목')),
                ('type', models.CharField(blank=True, choices=[('A', '구상'), ('B', '즉답'), ('C', '추가질문')], max_length=1)),
                ('presentation', models.TextField(blank=True, null=True, verbose_name='제시문')),
                ('question', models.TextField(blank=True, null=True, verbose_name='문제')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='정답')),
                ('big_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.bigsubject', verbose_name='대주제')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.region', verbose_name='지역')),
                ('scrapped_users', models.ManyToManyField(related_name='scrapped_problems', to=settings.AUTH_USER_MODEL, verbose_name='이 문제를 스크랩한 사람들')),
                ('small_subject', models.ManyToManyField(to='problem.smallsubject', verbose_name='소주제')),
            ],
            options={
                'verbose_name': '문제',
                'verbose_name_plural': '문제',
            },
        ),
    ]
