# Generated by Django 4.2 on 2024-06-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigsubject',
            options={'verbose_name': '대주제', 'verbose_name_plural': '대주제'},
        ),
        migrations.AlterModelOptions(
            name='smallsubject',
            options={'verbose_name': '소주제', 'verbose_name_plural': '소주제'},
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.problemset', verbose_name='문제 셋'),
        ),
        migrations.AlterField(
            model_name='smallsubject',
            name='big_subject',
            field=models.ForeignKey(blank=True, max_length=512, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='big_small_subjects', to='problem.bigsubject', verbose_name='대주제'),
        ),
    ]
