# Generated by Django 4.2 on 2024-06-23 18:01

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.utils


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_alter_bigsubject_options_alter_smallsubject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summernote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True, verbose_name='원본파일명')),
                ('file', models.FileField(unique=True, upload_to=django_summernote.utils.uploaded_filepath)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.problem', verbose_name='문제')),
            ],
            options={
                'verbose_name': '첨부 이미지',
                'verbose_name_plural': '첨부 이미지',
            },
        ),
    ]
