# Generated by Django 4.2 on 2024-06-29 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_summernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_problem_set', to='problem.problemset', verbose_name='문제 셋'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='small_subject',
            field=models.ManyToManyField(related_name='problem_small_subjects', to='problem.smallsubject', verbose_name='소주제'),
        ),
    ]
