# Generated by Django 4.2 on 2024-07-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_problem_presentation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='presentation_image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='', verbose_name='제시문 이미지', width_field='width'),
        ),
    ]
