# Generated by Django 4.2 on 2024-08-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_problem_height_problem_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='출제 문항 설명')),
                ('time_description', models.TextField(blank=True, null=True, verbose_name='제한시간 설명')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.region', verbose_name='지역')),
            ],
            options={
                'verbose_name': '실전 모의고사',
                'verbose_name_plural': '실전 모의고사',
            },
        ),
    ]
