# Generated by Django 4.2 on 2024-08-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_testset'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='색상'),
        ),
    ]
