# Generated by Django 4.2 on 2024-08-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_problem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_set',
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('P', '연습'), ('A', '실전')], max_length=1),
        ),
        migrations.AddField(
            model_name='problem',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='연도'),
        ),
    ]
