# Generated by Django 4.2 on 2024-08-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_remove_problem_problem_set_problem_problem_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='지역')),
            ],
            options={
                'verbose_name': '기출 출제 지역',
                'verbose_name_plural': '기출 출제 지역',
            },
        ),
        migrations.DeleteModel(
            name='ProblemSet',
        ),
    ]
