# Generated by Django 4.2 on 2024-08-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_remove_problem_color_problem_has_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='사진 url 링크'),
        ),
    ]
