# Generated by Django 4.2 on 2024-08-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_problem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallsubject',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='색상'),
        ),
    ]
