# Generated by Django 4.2 on 2024-08-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_smallsubject_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='제목')),
                ('color', models.CharField(blank=True, max_length=6, null=True, verbose_name='색상 코드')),
            ],
            options={
                'verbose_name': '색상',
                'verbose_name_plural': '색상',
            },
        ),
    ]
