# Generated by Django 4.2 on 2024-08-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0017_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='number_integer',
            field=models.IntegerField(blank=True, null=True, verbose_name='고유 번호 숫자'),
        ),
    ]
