# Generated by Django 4.2 on 2024-08-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0020_remove_problem_number_alter_problem_scrapped_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='number_integer',
            new_name='number',
        ),
    ]
