# Generated by Django 4.2 on 2025-09-21 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0021_rename_number_integer_problem_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(blank=True, max_length=5, null=True, verbose_name='방 번호')),
                ('region', models.CharField(blank=True, max_length=10, null=True, verbose_name='지역')),
                ('type', models.CharField(choices=[('구상형', 'A'), ('즉답형', 'B'), ('모의고사', 'C')], max_length=32, verbose_name='질문 타입')),
                ('problems', models.ManyToManyField(to='problem.problem', verbose_name='문제들')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='참여자')),
            ],
            options={
                'verbose_name': '스터디룸',
                'verbose_name_plural': '스터디룸',
            },
        ),
    ]
