# Generated by Django 4.2 on 2025-09-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0022_studyroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroom',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.region', verbose_name='지역'),
        ),
    ]
