# Generated by Django 4.2 on 2025-09-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0023_alter_studyroom_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='deep_link',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='딥링크 URL'),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='deep_link_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='딥링크 토큰'),
        ),
    ]
