# Generated by Django 4.2 on 2024-08-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
