# Generated by Django 4.2 on 2024-10-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_setting_options_remove_setting_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='블락 상태'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='버전'),
        ),
    ]
