# Generated by Django 4.2 on 2025-10-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_setting_is_blocked_alter_setting_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=32, null=True, verbose_name='버전')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='블락 상태')),
            ],
            options={
                'verbose_name': '버전',
                'verbose_name_plural': '버전',
            },
        ),
    ]
