# Generated by Django 4.2 on 2024-06-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='지역')),
                ('link', models.CharField(blank=True, max_length=1024, null=True, verbose_name='링크')),
            ],
            options={
                'verbose_name': '약관',
                'verbose_name_plural': '약관',
            },
        ),
    ]
