# Generated by Django 4.2 on 2024-06-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='제목'),
        ),
    ]
