# Generated by Django 4.2 on 2024-05-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phonelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
