# Generated by Django 4.2 on 2024-06-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_firebaselog_delete_phonelog_delete_pointlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebaselog',
            name='to',
        ),
        migrations.AddField(
            model_name='firebaselog',
            name='to',
            field=models.EmailField(blank=True, max_length=254, verbose_name='수신자'),
        ),
    ]
